routed_namespaces:
- vpn

addons:
  vpn:
    enabled: true
    type: wireguard
    configFileSecret: wireguard-config
    
settings:
  VPN_INTERFACE: wg0
  VPN_BLOCK_OTHER_TRAFFIC: true
  VPN_TRAFFIC_PORT: 1337