routed_namespaces:
- vpn

addons:
  vpn:
    enabled: true
    type: wireguard
    configFileSecret: wireguard-config
    
settings:
  NOT_ROUTED_TO_GATEWAY_CIDRS: "10.244.0.0/16 10.96.0.0/12"
  VPN_INTERFACE: wg0
  VPN_BLOCK_OTHER_TRAFFIC: true
  VPN_TRAFFIC_PORT: 1337
  VPN_LOCAL_CIDRS: "192.168.0.0/16 10.0.0.0/8 172.23.224.0/20"