ingress:
  main:
    enabled: true
    annotations:
      cert-manager.io/issuer: my-ca-issuer
    ingressClassName: nginx
    hosts:
      - host: localhost
        paths:
          - path: /jackett
    tls:
      - secretName: jackett
        hosts:
          - localhost
persistence:
  config:
    enabled: true
    type: pvc
    accessMode: ReadWriteOnce
    size: 128Mi